kind: Cluster
apiVersion: kind.sigs.k8s.io/v1alpha3
nodes:
- role: control-plane
- role: worker
  extraPortMappings:
  - containerPort: 30023
    hostPort: 3023
  - containerPort: 30026
    hostPort: 3026
  - containerPort: 30080
    hostPort: 3080
