
---
apiVersion: apiextensions.k8s.io/v1beta1
kind: CustomResourceDefinition
metadata:
  creationTimestamp: null
  name: githubs.teleport.gravitational.com
spec:
  additionalPrinterColumns:
  - JSONPath: .status.condition
    name: Condition
    type: string
  group: teleport.gravitational.com
  names:
    kind: GitHub
    plural: githubs
  scope: ""
  subresources:
    status: {}
  validation:
    openAPIV3Schema:
      description: GitHub is the Schema for the githubs API
      properties:
        apiVersion:
          description: 'APIVersion defines the versioned schema of this representation
            of an object. Servers should convert recognized schemas to the latest
            internal value, and may reject unrecognized values. More info: https://git.k8s.io/community/contributors/devel/api-conventions.md#resources'
          type: string
        kind:
          description: 'Kind is a string value representing the REST resource this
            object represents. Servers may infer this from the endpoint the client
            submits requests to. Cannot be updated. In CamelCase. More info: https://git.k8s.io/community/contributors/devel/api-conventions.md#types-kinds'
          type: string
        metadata:
          type: object
        spec:
          description: GitHubSpec defines the desired state of GitHub
          properties:
            client_id:
              description: ClientID is the Github OAuth app client ID
              type: string
            client_secret:
              description: ClientSecret is the Github OAuth app client secret
              type: string
            display:
              description: Display is the connector display name
              type: string
            redirect_url:
              description: RedirectURL is the authorization callback URL
              type: string
            teams_to_logins:
              description: TeamsToLogins maps Github team memberships onto allowed
                logins/roles
              items:
                description: TeamMapping represents a single team membership mapping
                properties:
                  kubernetes_groups:
                    description: KubeGroups is a list of allowed kubernetes groups
                      for this org/team
                    items:
                      type: string
                    type: array
                  logins:
                    description: Logins is a list of allowed logins for this org/team
                    items:
                      type: string
                    type: array
                  organization:
                    description: Organization is a Github organization a user belongs
                      to
                    type: string
                  team:
                    description: Team is a team within the organization a user belongs
                      to
                    type: string
                required:
                - organization
                - team
                type: object
              type: array
          required:
          - client_id
          - client_secret
          - display
          - redirect_url
          - teams_to_logins
          type: object
        status:
          description: GitHubStatus defines the observed state of GitHub
          properties:
            condition:
              type: string
            last_transition_time:
              format: date-time
              type: string
            reason:
              type: string
          required:
          - condition
          type: object
      type: object
  version: v1
  versions:
  - name: v1
    served: true
    storage: true
status:
  acceptedNames:
    kind: ""
    plural: ""
  conditions: []
  storedVersions: []
