
---
apiVersion: apiextensions.k8s.io/v1beta1
kind: CustomResourceDefinition
metadata:
  creationTimestamp: null
  name: roles.teleport.gravitational.com
spec:
  additionalPrinterColumns:
  - JSONPath: .status.condition
    name: Condition
    type: string
  group: teleport.gravitational.com
  names:
    kind: Role
    plural: roles
  scope: ""
  subresources:
    status: {}
  validation:
    openAPIV3Schema:
      description: Role is the Schema for the roles API
      properties:
        apiVersion:
          description: 'APIVersion defines the versioned schema of this representation
            of an object. Servers should convert recognized schemas to the latest
            internal value, and may reject unrecognized values. More info: https://git.k8s.io/community/contributors/devel/api-conventions.md#resources'
          type: string
        kind:
          description: 'Kind is a string value representing the REST resource this
            object represents. Servers may infer this from the endpoint the client
            submits requests to. Cannot be updated. In CamelCase. More info: https://git.k8s.io/community/contributors/devel/api-conventions.md#types-kinds'
          type: string
        metadata:
          type: object
        spec:
          description: RoleSpec defines the desired state of Role
          properties:
            allow:
              properties:
                kubernetes_groups:
                  items:
                    type: string
                  type: array
                logins:
                  items:
                    type: string
                  type: array
                node_labels:
                  additionalProperties:
                    items:
                      type: string
                    type: array
                  type: object
                rules:
                  items:
                    properties:
                      actions:
                        items:
                          type: string
                        type: array
                      resources:
                        items:
                          type: string
                        type: array
                      verbs:
                        items:
                          type: string
                        type: array
                      where:
                        type: string
                    type: object
                  type: array
              required:
              - logins
              type: object
            deny:
              properties:
                kubernetes_groups:
                  items:
                    type: string
                  type: array
                logins:
                  items:
                    type: string
                  type: array
                node_labels:
                  additionalProperties:
                    items:
                      type: string
                    type: array
                  type: object
                rules:
                  items:
                    properties:
                      actions:
                        items:
                          type: string
                        type: array
                      resources:
                        items:
                          type: string
                        type: array
                      verbs:
                        items:
                          type: string
                        type: array
                      where:
                        type: string
                    type: object
                  type: array
              required:
              - logins
              type: object
            options:
              description: 'INSERT ADDITIONAL SPEC FIELDS - desired state of cluster
                Important: Run "make" to regenerate code after modifying this file'
              properties:
                cert_format:
                  type: string
                client_idle_timeout:
                  format: int64
                  type: integer
                disconnect_expired_cert:
                  type: boolean
                forward_agent:
                  type: boolean
                max_session_ttl:
                  description: A Duration represents the elapsed time between two
                    instants as an int64 nanosecond count. The representation limits
                    the largest representable duration to approximately 290 years.
                  format: int64
                  type: integer
                port_forwarding:
                  type: boolean
              required:
              - cert_format
              - forward_agent
              type: object
          type: object
        status:
          description: RoleStatus defines the observed state of Role
          properties:
            condition:
              type: string
            last_transition_time:
              format: date-time
              type: string
            reason:
              type: string
          required:
          - condition
          type: object
      type: object
  version: v1
  versions:
  - name: v1
    served: true
    storage: true
status:
  acceptedNames:
    kind: ""
    plural: ""
  conditions: []
  storedVersions: []
